#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PODApp.Resource", IsApplication=true)]

namespace PODApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int IntelisenseIT = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo_galaxy_black_64 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int mail = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ProgressBarStyle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sample_0 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sample_1 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sample_2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sample_3 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int sample_4 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sample_5 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sample_6 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int sample_7 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Style_DB = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Style_Login = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int BtnClickCustPackingSlipJour = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int BtnClickDasBoardPSDB = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int BtnClickDocuRef = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int BtnClickLogisticPosAdd = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int BtnClickLogisticsLocation = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int BtnClickPackingSlipDetails = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int BtnClickPodPackingListFilterList = 2131165197;
			
			// aapt resource value: 0x7f07003e
			public const int BtnPSNDPodCam = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int BtnPSNDProcessPod = 2131165247;
			
			// aapt resource value: 0x7f070016
			public const int CustPSlipJourCT = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int CustPSlipJourDB = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int CustPSlipJourDR = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int CustPSlipJourIR = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int CustPSlipJourRR = 2131165208;
			
			// aapt resource value: 0x7f07001f
			public const int DocRefCD = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int DocRefCT = 2131165216;
			
			// aapt resource value: 0x7f070023
			public const int DocRefDR = 2131165219;
			
			// aapt resource value: 0x7f070021
			public const int DocRefIR = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int DocRefRR = 2131165218;
			
			// aapt resource value: 0x7f070032
			public const int LogLocationCD = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int LogLocationCT = 2131165235;
			
			// aapt resource value: 0x7f070036
			public const int LogLocationDR = 2131165238;
			
			// aapt resource value: 0x7f070034
			public const int LogLocationIR = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int LogLocationRR = 2131165237;
			
			// aapt resource value: 0x7f070029
			public const int LogPosAddressCD = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int LogPosAddressCT = 2131165226;
			
			// aapt resource value: 0x7f07002d
			public const int LogPosAddressDR = 2131165229;
			
			// aapt resource value: 0x7f07002b
			public const int LogPosAddressIR = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int LogPosAddressRR = 2131165228;
			
			// aapt resource value: 0x7f070004
			public const int PODmyButtonCam = 2131165188;
			
			// aapt resource value: 0x7f070045
			public const int PackingListFilterBtn = 2131165253;
			
			// aapt resource value: 0x7f070047
			public const int PackingListFilterlv = 2131165255;
			
			// aapt resource value: 0x7f070046
			public const int PackingListFiltersv = 2131165254;
			
			// aapt resource value: 0x7f07001b
			public const int PodDBCustPackSlipJourlv = 2131165211;
			
			// aapt resource value: 0x7f07002e
			public const int PodDBLogisticPostalAddresslv = 2131165230;
			
			// aapt resource value: 0x7f070024
			public const int PodDocReflv = 2131165220;
			
			// aapt resource value: 0x7f070005
			public const int PodImageViewCam = 2131165189;
			
			// aapt resource value: 0x7f070037
			public const int PodLogLocationlv = 2131165239;
			
			// aapt resource value: 0x7f07001a
			public const int PodPSgridview = 2131165210;
			
			// aapt resource value: 0x7f070052
			public const int RetrieveBtn = 2131165266;
			
			// aapt resource value: 0x7f070049
			public const int btnCreateDB = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int btnCreateSingle = 2131165258;
			
			// aapt resource value: 0x7f070003
			public const int btnDialogEmail = 2131165187;
			
			// aapt resource value: 0x7f07004b
			public const int btnList = 2131165259;
			
			// aapt resource value: 0x7f070041
			public const int btnSignIn = 2131165249;
			
			// aapt resource value: 0x7f070043
			public const int btnSignUp = 2131165251;
			
			// aapt resource value: 0x7f07003b
			public const int editText4 = 2131165243;
			
			// aapt resource value: 0x7f070054
			public const int gv = 2131165268;
			
			// aapt resource value: 0x7f070006
			public const int lblDashboard = 2131165190;
			
			// aapt resource value: 0x7f070048
			public const int linearLayout1 = 2131165256;
			
			// aapt resource value: 0x7f07004c
			public const int linearLayout2 = 2131165260;
			
			// aapt resource value: 0x7f07004f
			public const int linearLayout3 = 2131165263;
			
			// aapt resource value: 0x7f070050
			public const int nameEditText = 2131165264;
			
			// aapt resource value: 0x7f070044
			public const int progressBar1 = 2131165252;
			
			// aapt resource value: 0x7f070051
			public const int saveBtn = 2131165265;
			
			// aapt resource value: 0x7f070053
			public const int sv = 2131165267;
			
			// aapt resource value: 0x7f07004d
			public const int textView1 = 2131165261;
			
			// aapt resource value: 0x7f070014
			public const int txtCPSJDeliveryName = 2131165204;
			
			// aapt resource value: 0x7f07000f
			public const int txtCPSJDeviceId = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int txtCPSJPackingSlipId = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int txtCPSJQty = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int txtCPSJRecId = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int txtCPSJVolume = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int txtCPSJWeight = 2131165203;
			
			// aapt resource value: 0x7f070040
			public const int txtCreateAccount = 2131165248;
			
			// aapt resource value: 0x7f07001e
			public const int txtDRLocation = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int txtDRPackingSlipId = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int txtDRRecIdId = 2131165212;
			
			// aapt resource value: 0x7f07003a
			public const int txtEditPSNDAdd = 2131165242;
			
			// aapt resource value: 0x7f070039
			public const int txtEditPSNDDelAdd = 2131165241;
			
			// aapt resource value: 0x7f070038
			public const int txtEditPSNDDelName = 2131165240;
			
			// aapt resource value: 0x7f07003c
			public const int txtEditPSNDNetWeight = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int txtEditPSNDNoUnits = 2131165245;
			
			// aapt resource value: 0x7f070001
			public const int txtEmail = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int txtFirstName = 2131165184;
			
			// aapt resource value: 0x7f070031
			public const int txtLLLogDescription = 2131165233;
			
			// aapt resource value: 0x7f070030
			public const int txtLLLogLocation = 2131165232;
			
			// aapt resource value: 0x7f07002f
			public const int txtLLRecId = 2131165231;
			
			// aapt resource value: 0x7f070026
			public const int txtLPAAddress = 2131165222;
			
			// aapt resource value: 0x7f070028
			public const int txtLPALocation = 2131165224;
			
			// aapt resource value: 0x7f070025
			public const int txtLPARecId = 2131165221;
			
			// aapt resource value: 0x7f070027
			public const int txtLPAZipCode = 2131165223;
			
			// aapt resource value: 0x7f070042
			public const int txtOr = 2131165250;
			
			// aapt resource value: 0x7f070002
			public const int txtPassword = 2131165186;
			
			// aapt resource value: 0x7f07004e
			public const int txtResults = 2131165262;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_sign_up = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PodCameraScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PodDashBoard = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PodDashBoardMain = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PodDbCreate = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PodDBCustPackingSlipJour = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PodDBDocuRef = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PodDBLogisticPostalAddress = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PodDBLogisticsLocation = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PodDBPackingSlipNoDetails = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PodLoginScreen = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PodPackingListFilterList = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PodPerson = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SQLiteDatabasePOD = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int openCamera = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
