using System;
using System.Data;
using System.IO;
using SQLite;

namespace PODApp.Models
{
    /// <summary>
    /// SalesTable - SQLite Database
    /// </summary>
    public class SalesTable
    {
        public string BankAccount_LV { get; set; }
        public string BankCentralBankPurposeCode { get; set; }
        public string BankCentralBankPurposeText { get; set; }
        public string BankDocumentType { get; set; }
        public string CashDisc { get; set; }
        public string CashDiscBaseDate { get; set; }
        public string CashDiscPercent { get; set; }
        public string CommissionGroup { get; set; }
        public string ConsTarget_JP { get; set; }
        public string ContactPersonId { get; set; }
        public string CountyOrigDest { get; set; }
        public string CovStatus { get; set; }
        public string CreditCardApprovalAmount { get; set; }
        public string CreditCardAuthorization { get; set; }
        public string CreditCardAuthorizationError { get; set; }
        public string CreditCardCustRefId { get; set; }
        public string CreditNoteReasonCode { get; set; }
        public string CurBankAccount_LV { get; set; }
        public string CurrencyCode { get; set; }
        public string CustAccount { get; set; }
        public string CustBankAccount_LV { get; set; }
        public string CustGroup { get; set; }
        public string CustInvoiceId { get; set; }
        public string CustomerRef { get; set; }
        public string CustomsExportOrder_IN { get; set; }
        public string CustomsShippingBill_IN { get; set; }
        public string DAXIntegrationID { get; set; }
        public string Deadline { get; set; }
        public string DefaultDimension { get; set; }
        public string DEL_ConcessionContractId { get; set; }
        public string DEL_CreditCardProcessorTransactionId { get; set; }
        public string DEL_EntryCertificateRequired_W { get; set; }
        public string DEL_IssueOwnCertificate_W { get; set; }
        public string DEL_OMInternalOrganization { get; set; }
        public string DEL_RetailChannel { get; set; }
        public string DEL_RetailHourOfDay { get; set; }
        public string DEL_RetailOrder { get; set; }
        public string DEL_RetailPrepaymentOverridden { get; set; }
        public string DEL_RetailRetailStatusType { get; set; }
        public string DEL_RetailStoreId { get; set; }
        public string DEL_RetailTerminalId { get; set; }
        public string DeliveryDate { get; set; }
        public string DeliveryDateControlType { get; set; }
        public string DeliveryName { get; set; }
        public string DeliveryPostalAddress { get; set; }
        public string DirectDebitMandate { get; set; }
        public string DiscPercent { get; set; }
        public string DlvMode { get; set; }
        public string DlvReason { get; set; }
        public string DlvTerm { get; set; }
        public string DocumentStatus { get; set; }
        public string EInvoiceAccountCode { get; set; }
        public string EInvoiceLineSpec { get; set; }
        public string Email { get; set; }
        public string EndDisc { get; set; }
        public string EnterpriseNumber { get; set; }
        public string Estimate { get; set; }
        public string ExportReason { get; set; }
        public string FiscalDocType_PL { get; set; }
        public string FixedDueDate { get; set; }
        public string FixedExchRate { get; set; }
        public string FreightSlipType { get; set; }
        public string FreightZone { get; set; }
        public string GiroType { get; set; }
        public string InclTax { get; set; }
        public string InterCompanyAllowIndirectCreation { get; set; }
        public string InterCompanyAutoCreateOrders { get; set; }
        public string InterCompanyCompanyId { get; set; }
        public string InterCompanyDirectDelivery { get; set; }
        public string InterCompanyDirectDeliveryOrig { get; set; }
        public string InterCompanyOrder { get; set; }
        public string InterCompanyOriginalCustAccount { get; set; }
        public string InterCompanyOriginalSalesId { get; set; }
        public string InterCompanyPurchId { get; set; }
        public string IntrastatAddValue_LV { get; set; }
        public string IntrastatFulfillmentDate_HU { get; set; }
        public string InventLocationId { get; set; }
        public string InventSiteId { get; set; }
        public string InvoiceAccount { get; set; }
        public string InvoiceRegister_LT { get; set; }
        public string LanguageId { get; set; }
        public string LineDisc { get; set; }
        public string Listcode { get; set; }
        public string MarkupGroup { get; set; }
        public string MatchingAgreement { get; set; }
        public string MCROrderStopped { get; set; }
        public string MultiLineDisc { get; set; }
        public string NatureOfAssessee_IN { get; set; }
        public string NumberSequenceGroup { get; set; }
        public string OneTimeCustomer { get; set; }
        public string PackingSlipRegister_LT { get; set; }
        public string Payment { get; set; }
        public string PaymentSched { get; set; }
        public string PaymMode { get; set; }
        public string PaymSpec { get; set; }
        public string PdsBatchAttribAutoRes { get; set; }
        public string PdsCustRebateGroupId { get; set; }
        public string PdsRebateProgramTMAGroup { get; set; }
        public string Port { get; set; }
        public string PostingProfile { get; set; }
        public string PriceGroupId { get; set; }
        public string ProjId { get; set; }
        public string PurchId { get; set; }
        public string PurchOrderFormNum { get; set; }
        public string QuotationId { get; set; }
        public string ReceiptDateConfirmed { get; set; }
        public string ReceiptDateRequested { get; set; }
        public string ReleaseStatus { get; set; }
        public string Reservation { get; set; }
        public string ReturnDeadline { get; set; }
        public string ReturnItemNum { get; set; }
        public string ReturnReasonCodeId { get; set; }
        public string ReturnReplacementCreated { get; set; }
        public string ReturnReplacementId { get; set; }
        public string ReturnStatus { get; set; }
        public string SalesGroup { get; set; }
        public string SalesId { get; set; }
        public string SalesName { get; set; }
        public string SalesOriginId { get; set; }
        public string SalesPoolId { get; set; }
        public string SalesStatus { get; set; }
        public string SalesType { get; set; }
        public string SalesUnitId { get; set; }
        public string SettleVoucher { get; set; }
        public string ShipCarrierAccount { get; set; }
        public string ShipCarrierAccountCode { get; set; }
        public string ShipCarrierBlindShipment { get; set; }
        public string ShipCarrierDeliveryContact { get; set; }
        public string ShipCarrierDlvType { get; set; }
        public string ShipCarrierExpeditedShipment { get; set; }
        public string ShipCarrierFuelSurcharge { get; set; }
        public string ShipCarrierId { get; set; }
        public string ShipCarrierName { get; set; }
        public string ShipCarrierPostalAddress { get; set; }
        public string ShipCarrierResidential { get; set; }
        public string ShippingDateConfirmed { get; set; }
        public string ShippingDateRequested { get; set; }
        public string smmCampaignId { get; set; }
        public string smmSalesAmountTotal { get; set; }
        public string StatProcId { get; set; }
        public string TaxGroup { get; set; }
        public string TaxPeriodPaymentCode_PL { get; set; }
        public string TransactionCode { get; set; }
        public string Transport { get; set; }
        public string UnitedVATInvoice_LT { get; set; }
        public string URL { get; set; }
        public string VATNum { get; set; }
        public string WorkerSalesResponsible { get; set; }
        public string WorkerSalesTaker { get; set; }
        public string modifiedDateTime { get; set; }
        public string dEL_ModifiedTime { get; set; }
        public string modifiedBy { get; set; }
        public string modifiedTransactionId { get; set; }
        public string createdDateTime { get; set; }
        public string dEL_CreatedTime { get; set; }
        public string createdBy { get; set; }
        public string createdTransactionId { get; set; }
        public string dataAreaId { get; set; }
        public string recVersion { get; set; }
        public string Partition { get; set; }
        public string RecId { get; set; }
    }
}